name: meow
description: A new Flutter package project.
version: 0.0.1
homepage: https://ggdream.github.io
repository: https://github.com/ggdream/meow
issue_tracker: https://github.com/ggdream/meow/issues


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  get: 4.3.8
  hashids2: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  get_cli: 1.6.0


flutter:
  uses-material-design: true
